import CheckboxGroupFieldItem from './CheckboxGroupField';
import InputFieldItem from './InputField';
import TextareaFieldItem from './TextareaField';
import ImageFieldItem from './ImageField';
import ColorPickerFieldItem from './ColorPickerField';
import DateRangeFieldItem from './DateRangeField';
import TimePickerFieldItem from './TimePickerField';
import InputSelectFieldItem from './InputSelectField';
import InputMultiSelectFieldItem from './InputMultiSelectField';
import InputWithCheckboxFieldItem from './InputWithCheckboxField';
import TextareaWithCheckboxFieldItem from './TextareaWithCheckboxField';
import InputSelectWithCheckboxFieldItem from './InputSelectWithCheckboxField';
import KeywordsFieldItem from './KeywordsField';
import ImageListFieldItem from './ImageListField';
import LinkListFieldItem from './LinkListField';
import SubClusterListFieldItem from './SubClusterListField';
import EmployeeListFieldItem from './EmployeeListField';
import ContentMenuFieldItem from './ContentMenuField';
import PageAccessFieldItem from './PageAccessField';
import InputTypeFieldItem from './InputTypeField';
import QRField from './QRField';
import EventType from './EventType';
import SingleRowInputWithCheckboxField from './SingleRowInputCheckboxField';

export const CheckboxGroupField = CheckboxGroupFieldItem;
export const InputField = InputFieldItem;
export const TextareaField = TextareaFieldItem;
export const ImageField = ImageFieldItem;
export const ColorPickerField = ColorPickerFieldItem;
export const DateRangeField = DateRangeFieldItem;
export const TimePickerField = TimePickerFieldItem;
export const InputSelectField = InputSelectFieldItem;
export const InputMultiSelectField = InputMultiSelectFieldItem;
export const InputWithCheckboxField = InputWithCheckboxFieldItem;
export const TextareaWithCheckboxField = TextareaWithCheckboxFieldItem;
export const InputSelectWithCheckboxField = InputSelectWithCheckboxFieldItem;
export const KeywordsField = KeywordsFieldItem;
export const ImageListField = ImageListFieldItem;
export const LinkListField = LinkListFieldItem;
export const EmployeeListField = EmployeeListFieldItem;
export const ContentMenuField = ContentMenuFieldItem;
export const PageAccessField = PageAccessFieldItem;
export const SubClusterListField = SubClusterListFieldItem;
export const InputTypeField = InputTypeFieldItem;
export const QRFiled = QRField;
export const SingleRowInputCheckboxField = SingleRowInputWithCheckboxField;
// export const EventType = EventType
