apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{.Release.Name}}
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`{{.Release.Name}}.synkd.life`)
    kind: Rule
    services:
    - name: {{.Release.Name}}
      port: 80
  tls:
    certResolver: myresolver